#微服务端口号
server:
  port: 8762

#指定eureka服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#spring配置
spring:
  application:
    name: springcloud-eurekaclient

